version: 1.0.{build}

configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}.0'
  assembly_file_version: '{version}.0'
  assembly_informational_version: '{version}-alpha'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

deploy:
- provider: NuGet
  server: https://www.myget.org/F/stream-importer/
  api_key:
    secure: HkUu/oXf5EDtX4PJXE+mQtwxPI6d1uwLt0KqVbeUKPREBqD69PxduVla2FiGQCug
  symbol_server: https://nuget.symbolsource.org/MyGet/stream-importer