version: 0.8.0

configuration: Release

install:
  - ps: $env:GIT_HASH = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10)

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-pre{build}-$(GIT_HASH)'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

deploy:
- provider: NuGet
  server: https://www.myget.org/F/stream-importer/
  api_key:
    secure: HkUu/oXf5EDtX4PJXE+mQtwxPI6d1uwLt0KqVbeUKPREBqD69PxduVla2FiGQCug
  symbol_server: https://nuget.symbolsource.org/MyGet/stream-importer